# LLM配置
llm:
  api_url: 'https://open.bigmodel.cn/api/paas/v4/chat/completions'
  max_context_length: 10
  temperature: 0.7
  model: 'glm-4'
  device: 'cpu'
  top_p: 0.7

# ASR配置
asr:
  model: 'damo/SenseVoiceSmall'
  device: 'cpu'
  vad_model: 'fsmn-vad'
  vad_params:
    max_single_segment_time: 30000
    min_silence_duration_ms: 500
    speech_pad_ms: 100
  audio:
    target_sr: 16000
    channels: 1
    sample_width: 2

# TTS配置
tts:
  voices:
    en: 'en-US-JennyNeural'
    zh: 'zh-CN-XiaoxiaoNeural'
  rate: '+0%'
  volume: '+20%'
  pitch: '+0Hz'
  temp_dir: 'temp/tts_cache'
  cleanup:
    max_age_hours: 1

# Server配置
server:
  host: '0.0.0.0'
  port: 8000
  debug: false

# WebSocket配置
websocket:
  ping_interval: 30
  ping_timeout: 30
  close_timeout: 30

# Logging配置
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s' 